
# inherit from the proprietary version
-include vendor/MediaTek/k0708/BoardConfigVendor.mk

LOCAL_PATH := device/MediaTek/k0708


TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := ture
TARGET_BOARD_PLATFORM := mt6582
MTK_BOARD_PLATFORMS := mt6582
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_ARCH_VARIANT_CPU := cortex-a7
#TARGET_BOARD_PLATFORM_GPU := mali-400 MP
TARGET_CPU_VARIANT := generic
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true

BOARD_USES_MTK_HARDWARE := true
BOARD_HAS_MTK_HARDWARE := true
BOARD_HAS_MTK:=true

TARGET_BOOTLOADER_BOARD_NAME := k0708

# fix this up by examining /proc/mtd on a running device
TARGET_USERIMAGES_USE_EXT4 := true
#TARGET_USERIMAGES_USE_F2FS := true
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216
BOARD_FLASH_BLOCK_SIZE := 512

TARGET_PREBUILT_KERNEL := device/MediaTek/k0708/kernel
BOARD_HAS_NO_SELECT_BUTTON := true

TARGET_RECOVERY_FSTAB := device/MediaTek/k0708/recovery/root/etc/recovery.fstab
BOARD_CUSTOM_BOOTIMG := true
#BOARD_CUSTOM_MKBOOTIMG := $(HOST_OUT_EXECUTABLES)/mtkbootimg$(HOST_EXECUTABLE_SUFFIX)
#BOARD_CUSTOM_BOOTIMG_MK := device/MediaTek/k0708/bootimg.mk
#BOARD_MKBOOTIMG_ARGS := --mtk 1

TW_EXTRA_LANGUAGES := true
TW_DEFAULT_LANGUAGE := en_US

#TW_NO_REBOOT_BOOTLOADER := true
#TW_NO_REBOOT_RECOVERY := true
#TW_NO_USB_STORAGE := true

# TWRP
RECOVERY_GRAPHICS_USE_LINELENGTH := true
RECOVERY_VARIANT := twrp
TW_NO_EXFAT := true
TWHAVE_SELINUX := true
TW_THEME := landscape_mdpi
TW_NO_EXFAT_FUSE := true
TW_USE_MODEL_HARDWARE_ID_FOR_DEVICE_ID := true
TARGET_USE_CUSTOM_LUN_FILE_PATH := "/sys/devices/platform/mt_usb/musb-hdrc.0/gadget/lun%d/file"
TARGET_RECOVERY_PIXEL_FORMAT := "BRGA_8888"
TW_EXCLUDE_SUPERSU := true
TW_INPUT_BLACKLIST := "hbtp_vm"
#TW_SCREEN_BLANK_ON_BOOT := true
TW_NO_SCREEN_BLANK := true
#DEVICE_RESOLUTION := 800x480
DEVICE_RESOLUTION := 1024x600
TARGET_SCREEN_HEIGHT := 600
TARGET_SCREEN_WIDTH := 1024
BOARD_HAS_LOW_RESOLUTION := true
#TARGET_SCREEN_HEIGHT := 480
#TARGET_SCREEN_WIDTH := 800
#LANDSCAPE_RESOLUTION := 1024x600
TW_DEFAULT_ROTATION := 270
TW_BRIGHTNESS_PATH := /sys/class/leds/lcd-backlight/brightness
TW_MAX_BRIGHTNESS := 255
TW_DEFAULT_BRIGHTNESS := 80
TW_INCLUDE_NTFS_3G := true
TW_INCLUDE_FUSE_EXFAT := true
TWRP_INCLUDE_LOGCAT := true
TW_INCLUDE_FB2PNG := true
TW_CUSTOM_CPU_TEMP_PATH := /sys/devices/virtual/thermal/thermal_zone1/temp
TW_INCLUDE_JPEG := true

#BOARD_HAS_NO_REAL_SDCARD := true
BOARD_SUPPRESS_SECURE_ERASE := true
BOARD_HAS_NO_MISC_PARTITION := true
BOARD_RECOVERY_SWIPE := true
BOARD_USES_MMCUTILS := true
BOARD_SUPPRESS_EMMC_WIPE := true

RECOVERY_TOUCHSCREEN_SWAP_XY := true
RECOVERY_TOUCHSCREEN_FLIP_Y := true
#RECOVERY_TOUCHSCREEN_FLIP_X := true
#BOARD_HAS_FLIPPED_SCREEN := true

#TW_INTERNAL_STORAGE_PATH := "/sdcard"
#TW_INTERNAL_STORAGE_MOUNT_POINT := "sdcard"

TW_INTERNAL_STORAGE_PATH := "/storage/sdcard0"
TW_INTERNAL_STORAGE_MOUNT_POINT := "sdcard0"

#TW_INTERNAL_STORAGE_PATH := "/data/media"
#TW_INTERNAL_STORAGE_MOUNT_POINT := "data"
RECOVERY_SDCARD_ON_DATA := true

#TW_INTERNAL_STORAGE_PATH := "/emmc"
#TW_INTERNAL_STORAGE_MOUNT_POINT := "emmc"
TW_EXTERNAL_STORAGE_PATH := "/storage/sdcard1"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "sdcard1"
#TW_INCLUDE_JB_CRYPTO := true
TW_INCLUDE_CRYPTO := true
#TW_INCLUDE_L_CRYPTO := true
TW_CRYPTO_FS_TYPE := "ext4"
TW_CRYPTO_REAL_BLKDEV := "/dev/block/mmcblk0p7"
TW_CRYPTO_MNT_POINT := "/data"
TW_CRYPTO_FS_OPTIONS := "nosuid,nodev,noatime,discard,noauto_da_alloc,data=ordered"
TW_CRYPTO_FS_FLAGS := "0x00000406"
TW_CRYPTO_KEY_LOC := "/efs/metadata"


#include $(LOCAL_PATH)/kernel.mk
#以下があるとランチが別になる5.1以降。
#include device/generic/twrpbuilder/BoardConfig32.mk
